version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"   # наружу 8080, внутри у тебя EXPOSE 80
    networks:
      - appnet

  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 "
    ports:
      - "5173:5173"
      - "5174:5174"
    environment:
      - NODE_ENV=development
    networks:
      - appnet
    depends_on:
      - backend

networks:
  appnet:
    driver: bridge

